### ISSUE TITLE
Edit imported pages

### ISSUE THREAD

**Issue by libantas** [zadam/trilium-web-clipper#19]
I see that when you import webpages to trilium you cannot edit them.

**Comment by zadam** [comment]
I assume you see something like this?

![](https://user-images.githubusercontent.com/617641/91231547-b980ec00-e72d-11ea-8004-43cf7469ad58.png)

Just click on "Click here" and you can edit the page.

To be clear this shows up not because the page is imported but because it is too long and can take some time to load so as an optimization we first show the read only view first.

**Comment by meichthys** [comment]
@zadam  I think we can close this.
